baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "mcchiu blogthingv2"
#theme = "anatole"
summarylength = 140
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-131046266-1"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[module]
    [[module.imports]]
    path = "github.com/lxndrblz/anatole"

[permalinks]
    blog = "/blog/:year/:slug/"
    page = "/:slug/"

##  settings  -------------------------------------------------------------------------------------

[params]
title = "mcchiu blogthingv2"
author = "michael chiu"
#copyright = "2020-2021"
description = """ big dreamer in a realist's body with not much to show for it """
# i verb nouns || F/A for ??? 
profilePicture = "images/avatar.png"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = ["css/custom.css"]
# example ["js/custom.js"]
customJs = [] 
mainSections = ["blog"]
images = []
doNotLoadAnimations = true
# Form Spree Contact Form
contactFormAction = "https://formspree.io/f/mjvjvzaj"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

indexDateFormat = "2006 Jan 2"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"


# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings  -------------------------------------------------------------------------------------
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links ---------------------------------------------------------------------------------------
# use 'fab' when brand icons, use 'fas' when standard solid icons.

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/cassist/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:contact@mcchiu.ca"

#[[params.socialIcons]]
#icon = "fab fa-instagram"
#title = "instagram"
#url = "https://www.instagram.com/"

#[[params.socialIcons]]
#icon = "fab fa-linkedin"
#title = "Linkedin"
#url = "https://de.linkedin.com/"


## Menu items  ---------------------------------------------------------------------------------------

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"
